[Appearance]
icon_theme=breeze
style=Fusion

[Fonts]
fixed=@Variant(\0\0\0@\0\0\0\x12JetBrains Mono\0\0\0\0\0\0\0\0\0\xd2\0\0\0\n\0\0\0\0)
general=@Variant(\0\0\0@\0\0\0\x8Inter\0\0\0\0\0\0\0\0\0\xd2\0\0\0\n\0\0\0\0)
