# === EDITOR ===
EDITOR=nvim
VISUAL=nvim

# === XDG ===
XDG_CONFIG_HOME=/home/ForeverLX/.config

# === CUDA ===
PATH=/opt/cuda/bin:/home/ForeverLX/.local/bin:%E{PATH}
LD_LIBRARY_PATH=/opt/cuda/lib64

=== Virtual Machines ===
LIBVIRT_DEFAULT_URI="qemu:///system"
