# === QT ===
QT_QPA_PLATFORMTHEME=qt6ct

# === EDITOR ===
EDITOR=nvim
VISUAL=nvim

# === CONTAINER RUNTIME ===
DOCKER_HOST=unix:///run/user/1002/podman/podman.sock

# === XDG ===
XDG_CONFIG_HOME=/home/ForeverLX/.config

# === CUDA ===
PATH=/opt/cuda/bin:/home/ForeverLX/.local/bin:%E{PATH}
LD_LIBRARY_PATH=/opt/cuda/lib64

export LIBVIRT_DEFAULT_URI="qemu:///system"
