# ~/.config/fuzzel/fuzzel.ini
# Fuzzel Configuration - NightForge

[main]
dpi-aware=yes
font=MesloLGS NF:size=14
prompt=" ❯ "
icon-theme=Papirus-Dark
icons-enabled=yes
fields=name,generic,comment,categories,filename,keywords
match-mode=fuzzy
show-actions=yes
terminal=ghostty -e
lines=12
width=55
inner-pad=12
horizontal-pad=30
vertical-pad=12
match-counter=yes
include=~/.config/fuzzel/colors.ini

[dmenu]
exit-immediately-if-empty=yes
